
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mcfxqvnqzsiycgfjdbay.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1jZnhxdm5xenNpeWNnZmpkYmF5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzMjEzNjQsImV4cCI6MjA1OTg5NzM2NH0.71WXQ_MsO_4BYx786VRd8cmlNGoNrmTYf5kvMUZ-iks";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
